// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Observable",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Observable",
            targets: ["AppModule"],
            bundleIdentifier: "test.wwdcssc",
            teamIdentifier: "VGKCD7Q8NW",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This app requires access to the Camera."),
                .fileAccess(.pictureFolder, mode: .readWrite),
                .fileAccess(.moviesFolder, mode: .readWrite),
                .photoLibrary(purposeString: "This app requires access to the photo library."),
                .photoLibraryAdd(purposeString: "This app requires access to the photo library.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)